fix: yml indentation problem

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Push to PWS
+name: Push to PWS 
 
 on:
   push:
@@ -19,15 +19,18 @@ jobs:
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         
     - name: Push to PWS
-        env:
-          PWS_URL: ${{ secrets.PWS_URL }}
-        run: |
-            current_branch=$(git branch --show-current)
-            echo "Current branch: $current_branch"
-      
-            push_output=$(git push $PWS_URL $current_branch:$current_branch 2>&1)
-            if [[ $? -ne 0 ]]; then
-              echo "Push failed with output: $push_output"
-              exit 1
-            fi
-            echo "Push successful with output: $push_output"
+      env:
+        PWS_URL: ${{ secrets.PWS_URL }}
+      run: |
+          # Get current branch name
+          current_branch=$(git branch --show-current)
+          echo "Current branch: $current_branch"
+          
+          # Push current branch to PWS master branch
+          push_output=$(git push $PWS_URL $current_branch:master 2>&1)
+          if [[ $? -ne 0 ]]; then
+            echo "Push failed with output: $push_output"
+            echo "Error: Unable to push changes. Please check the error message above and resolve any conflicts manually."
+            exit 1
+          fi
+          echo "Push successful with output: $push_output"
